name: CI
on: [push]
jobs: 
 sast_scan:
  name: Run Bandit Scan
  runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: set uo python
    uses: actions/setup-python@v2
    with:
       python-version: 3.8
  - name: install bandit
    run: pip install bandit

  - name: Run Bandit Scan
    run: bandit -ll -ii -r . -f json -o bandit-report.json
  - name: Upload Artifact
    uses: actions/upload-artifact@v3
    if: always()
    with:
     name: bandit-findings
     path: bandit-report.json
 
 image_scan:
  name: Build Image and Run Image Scan
  runs-on: ubuntu-latest

  steps:
  - name: checkout code
    uses: actions/checkout@v2
  - name: setting up Docker
    uses: docker-practice/actions-setup-docker@v1
    with:
     docker_version: '20.10.7'

     
  - name: Build Docker Image
    run: docker build -f Dockerfile -t myapp:latest .

  - name: Docker Scout Scan
    run: |
      curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
      sh install-scout.sh
      echo ${{ secrets.REPO_PWD }} | docker login -u ${{ secrets.REPO_USER }} --password-stdin
      docker scout quickview --output sarif --output-file quickview-report.sarif
      docker scout cves --output sarif --output-file cve-report.sarif
   

  - name: Tag Docker Image
    run: docker tag myapp:latest imahamed/lab10:latest

  - name: Push Docker Image
    run: docker push imahamed/lab10:latest
    

    
  - name: Upload Artifact 1
    uses: actions/upload-artifact@v3
    if: always()
    with:
      name: cve-report
      path: cve-report.sarif
      
  - name: Upload Artifact 2
    uses: actions/upload-artifact@v3
    if: always()
    with:
      name: quickview-report
      path: quickview-report.sarif


 
