name: CI
on: [push]
jobs: 
 sast_scan:
  name: Run Bandit Scan
  runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v2
  - name: set uo python
    uses: actions/setup-python@v2
    with:
       python-version: 3.8
  - name: install bandit
    run: pip install bandit

  - name: Run Bandit Scan
    run: bandit -ll -ii -r . -f json -o bandit-report.json
  - name: Upload Artifact
    uses: actions/upload-artifact@v3
    if: always()
    with:
     name: bandit-findings
     path: bandit-report.json
 
 image_scan:
  name: Build Image and Run Image Scan
  runs-on: ubuntu-latest

  steps:
  - name: checkout code
    uses: actions/checkout@v2
  - name: setting up Docker
    uses: docker-practice/actions-setup-docker@v1
    with:
     docker_version: '20.10.7'

     
  - name: Build Docker Image
    run: docker build -f Dockerfile -t myapp:latest .

  - name: Docker Scout Scan
    uses: docker/scout-action@v1.4.1
    with:
      dockerhub-user: ${{ secrets.REPO_USER }}
      dockerhub-password: ${{ secrets.REPO_PWD }}
      command: quickview,cves
      only-severities: critical,high
      sarif-file: scout-report.sarif

  - name: Tag Docker Image
    run: docker tag myapp:latest imahamed/lab10:latest

  - name: push docker build to repository
    run: docker push imahamed/lab10:latest
    
  - name: permission
    run: chmod 400 ${{ secrets.SSH_KEY }}

  - name: Creating webserver
    run: |
      ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_KEY }} root@165.227.34.115 "
      docker login -u ${{ secrets.REPO_USER }} -p ${{ secrets.REPO_PWD }} &&
      docker ps -aq | xargs -r docker stop | xargs -r docker rm &&
      docker run -d -p 8000:8000 imahamed/lab10:v2"
      
    
  - name: Upload Artifact
    uses: actions/upload-artifact@v3
    if: always()
    with:
       name: docker-scout-findings
       path: scout-report.sarif

